apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
	name: akcluster
	region: ap-south-1

nodeGroups:
	- name: ng1
	  desiredCapacity: 2
	  instanceType: t2.micro
	  ssh:
		publicKeyName: mykey111222
	- name: ng2
	  desiredCapacity: 1
	  instanceType: t2.small
	  ssh:
		publicKeyName: mykey111222
	- name: ng-mixed
	  minSize: 2
	  maxSize: 5
	  instanceDistribution: 
		maxPrice: 0.017
		instanceTypes: ["t3.small","t3.medium"]
		onDemandBaseCapacity: 0
		onDemandPercentageAboveBaseCapacity: 50
		spotInstancesPools: 2
	  ssh:
		publicKeyName: mykey111222
	