apiVersion: v1
kind: Deployment
  name: rsweb
spec:
  replicas: 1
  selector:
    matchLabels:
      dc: IN
  template:
    metadata:
      name: mypod1
      labels:
        env: dev	
    spec:
      containers:
      - name: "mycon1"
        image: "akshit07/webserver:v1"