apiVersion: v1
kind: ReplicaSet
  name: mysql_rs
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: mysqlpod1
      labels:
        env: dev	
    spec:
      containers:
      - name: "mysql"
        image: "mysql:5.6"
        env:
	  - name: MYSQL_ROOT_PASSWORD
            value: redhat
	  - name: MYSQL_DATABASE
            value: mydb
	  - name: MYSQL_USER
            value: akshit
	  - name: MYSQL_PASSWORD
            value: redhat