apiVersion: v1
kind: ReplicaSet
  name: mysql_rs
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: mysqlpod1
      labels:
        env: dev	
    spec:
      containers:
      - name: "mysql"
        image: "mysql:5.6"
        env:
	  - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name:mysqlsecret
                key: rpass
	  - name: MYSQL_DATABASE
            value: mydb
	  - name: MYSQL_USER
            valueFrom: 
              secretKeyRef:
                name:mysqlsecret
                key: username
	  - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                name:mysqlsecret
                key: apass
        volumeMounts:
        - name: web1-vol1
     	  mountPath : /var/lib/sql
      volumes:
      - name: web-vol1
        persistentVolumeClaim:
        claimName: mypvc1