apiVersion: v1
kind: pod

metadata:
  name: mypod1
  labels:
    env: dev
    dc: IN
spec:
  containers:
  - name: "mycon1"
    image: "akshit/apache-webserver"
    volumeMounts:
    - name: web1-vol1
      mountPath : /var/www/html
  volumes:
  - name: web-vol1
    persistentVolumeClaim:
      claimName: mypvc1        