apiVersion: v1
kind: ReplicationController
metadata:
  name: rcweb

spec:
  replicas: 1
  selector:
    dc: IN
  template:
    metadata:
      name: mypod1
      labels:
        env: dev
        dc: IN
    spec:
      containers:
      - name: "mycon1"
        image: "akshit/apache-webserver"