apiVersion: v1
kind: ReplicaSet
  name: rsweb
spec:
  replicas: 1
  selector:
    matchLabels:
      dc: IN
      env: prod
      app: webserver
    matchExpressions:
      - { key: dc, operator: In, values: [ IN, US] }
      - { key: env, operator: In, values: [ dev]}
      - { key: app, operator: In, values: [ webserver ] }
  template:
    metadata:
      name: mypod1
      labels:
        env: dev
        dc: IN	
    spec:
      containers:
      - name: "mycon1"
        image: "akshit/apache-webserver"
        env:
	  - name: x
            value: something